---
apps:
  replicaCount: 3

  image:
    tag: "<IMAGE_TAG>"

  prefixName: "prod"

  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

  ingress:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: my-api-uwu.detectionserver.site
        paths:
          - path: /
            pathType: ImplementationSpecific

  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

  nodeSelector:
    kubernetes.io/type: node-worker
