name: "Pipeline to deploy GoApp: Prod Env"
on:
  push:
    tags:
      - "v*.*.*-go" # goapp-v1.x.x

env:
  REGISTRY: ghcr.io/iv1310
  IMAGE_API_NAME: my-api-uwu

jobs:
  go-main-pipeline:
    name: Doing some test on GO App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_API_NAME }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Log in to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./my-api-uwu/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_API_NAME }}:stable,${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Get tag
        id: gettag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0-go
      - name: Set envar
        run: |
          newTag=$(echo "${{ steps.gettag.outputs.tag }}" | sed 's/^v//')
          echo "NEW_TAG=$newTag" >> $COMMIT_ENV
      - uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.40.5
      - name: Replace image tag
        run: |
          yq eval '.apps.image.tag = "${{ env.NEW_TAG }}"' -i my-api-uwu/helm-charts/values-prod.yaml
      - name: deploy go app to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            helm dependency build my-api-uwu/helm-charts
            helm upgrade --install my-api-uwu -n prod-my-api-uwu my-api-uwu/helm-charts -f my-api-uwu/helm-charts/values.yaml -f my-api-uwu/helm-charts/values-prod.yaml
